name: Run Apex Tests - Dev Org

# Dispara quando houver push na branch dev e também agendado
on:
  push:
    branches:
      - main

jobs:
  run-apex-tests:
    runs-on: ubuntu-latest

    steps:
    
    # 2️⃣ Instalar Salesforce CLI
    - name: Install Salesforce CLI
      run: |
        npm install -g sfdx-cli
        sfdx --version

    # 3️⃣ Autenticar na org Dev usando username + password + security token
    - name: Authenticate to Salesforce Dev Org
      env:
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_SERVERURL: ${{ secrets.SF_SERVERURL }}  # Sandbox: https://test.salesforce.com
      run: |
        sfdx auth:jwt:grant --clientid <SF_CLIENT_ID> --jwtkeyfile server.key --username <SF_USERNAME> --instanceurl https://test.salesforce.com

    # 4️⃣ Rodar todos os testes Apex
    - name: Run Apex Tests
      run: |
        sfdx force:apex:test:run --resultformat junit --wait 10 --outputdir ./test-results
        cat ./test-results/test-result-*.xml || echo "No test results found"

    # 5️⃣ Upload dos resultados para GitHub Actions
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: apex-test-results
        path: ./test-results
