name: Run Apex Tests - Dev Org
 
on:
  push:
    branches:
      - main
jobs:
  run-apex-tests:
    runs-on: ubuntu-latest

    steps:
	
	- name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
    
    # 2️⃣ Instalar Salesforce CLI
    - name: Install Salesforce CLI
      run: |
        npm install -g @salesforce/cli
        sfdx --version

    # 3️⃣ Autenticar na org via JWT
    - name: Authenticate via JWT
      env:
        SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_SERVERURL: ${{ secrets.SF_SERVERURL }}
        SF_JWT_KEY: ${{ secrets.SF_JWT_KEY }}
      run: |
        echo "$SF_JWT_KEY" > server.key
        chmod 600 server.key
        sfdx force:auth:jwt:grant --clientid $SF_CLIENT_ID --jwtkeyfile server.key --username $SF_USERNAME --instanceurl $SF_SERVERURL
        sfdx force:config:set defaultusername=$SF_USERNAME --global
        sfdx force:org:display
        
		
	 - name: Install Salesforce Code Analyzer
        run: |
          npm install -g @salesforce/sfdx-scanner
          sfscanner --version

	- name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: code-analysis.sarif


    # 4️⃣ Rodar todos os testes Apex
    - name: Run Apex Tests
      id: apex_tests
      run: |
        sfdx force:apex:test:run --resultformat human --wait 10 --outputdir ./test-results --codecoverage
        ls ./test-results
        cat ./test-results/test-result-*.xml || echo "No test results found"

    # 5️⃣ Upload dos resultados de teste
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: apex-test-results
        path: ./test-results

    # 6️⃣ Falhar a pipeline se houver testes falhos
    - name: Fail if tests failed
      if: always()
      run: |
        FAILED=$(grep -L "<failure>" ./test-results/test-result-*.xml || echo "")
        if [ -n "$FAILED" ]; then
          echo "Some tests failed. Check the uploaded test results."
          exit 1
        else
          echo "All tests passed."
